DEVELOPMENT.md, README.md, pkg/config/config.go, pkg/splunk/splunk.go
Replaces password auth with token auth for the Splunk API:
* Updated config parsing for tokens, removing username and password
* Updated Splunk pkg code to connect via Bearer token
* Updated README.md and DEVELOPMENT.md with token info
=> Replace Splunk password auth with token auth

.gitignore
This adds the Visual Studio Code local config directory (.vscode/) to the
repository .gitignore file.
=> Adds local editor config (.vscode) to gitignore

pkg/listeners/listeners.go
This removes the logline print from listerns.go of the Alert.Result.Raw field, which no
longer exists after #10.
=> Minor fix for bug introduced by Alerts refactor

DEVELOPMENT.md, go.mod, go.sum, pkg/config/config.go, pkg/jira/jira.go, pkg/ldap/ldap.go, pkg/listeners/listeners.go, pkg/listeners/listeners_test.go
After processing a splunk webhook and looking up the user/manager in LDAP, a new ticket will be created in Jira based on the parameters in the config file.
- Ticket Summary: will always be `Compliance Alert: SRE Cluster Admin Elevation` as of right now, but open to making this a config property
- Ticket Description: I'll need to know what our splunk webhooks look like to finish this off, but there's sample text for now.
- Ticket Labels: Each created ticket will get three labels:
- `compliance-audit-router-managed`: this signifies that CAR is managing the tickets. It also has the added benefit that we can set up the Jira webhook scope with very simple JQL of `labels = compliance-audit-router-managed` 
- `compliance-audit-router/manager:<manager_account_id>`: the Jira account ID of the …
=> Add jira integration

DEVELOPMENT.md
This adds info to the DEVELOPMENT.md file about Splunk Alert SIDs and webhook payloads, and retrieval of search results.
=> Adds Splunk alert webhook payload and result retrieval info

OWNERS, OWNERS_ALIASES
Adds an OWNERS_ALIASES file to CAR to clean up the long lists of folks.
=> ADDS OWNERS_ALIASES file

.gitignore
Adds build output directory to .gitignore
=> Add build output directory to .gitignore

Makefile
Adds helper target to list make targets to the Makefile.
Usage:
```
$ make list
egrep: warning: egrep is obsolescent; using grep -E
all
boilerplate-commit
boilerplate-freeze-check
boilerplate-update
build
build/_output/compliance-audit-router
clean
default
isclean
osd-container-image-build
osd-container-image-build-push
osd-container-image-build-push-one
osd-container-image-login
osd-container-image-push
prow-config
serve
test
vet
```
=> Adds helper to Makefile

DEVELOPMENT.md, Makefile, compose.yaml, pkg/config/config.go
Update config load to look for a config file in the current working directory, as a configmap would be placed in production.
Add a make target for local image builds with mimicing the boilerplate
build, but usinng localhost friendly names for use with compose.
Add a compose yaml for easy container development.
Add documentation for the compose and image build setup to
DEVELOPMENT.md
=> Update config location ; add compose yaml and local image build make target and docs

cmd/main.go, pkg/config/config.go, pkg/listeners/listeners.go
- add dry run
- makes minor linter changes
- adds verbose logging; moves logging before metrics for better tracing
- finalize dry-run for processAlertHandler
- add template validation test on startup
- add more verbose output to main.go
- add error handling for failed splunk search; move verbose logging
- add more details on splunk api access to DEVELOPMENT.md
- fix incorrect number of arguments to metric creation
- handle case for empty "reason" field
- fix splunk alert retrieval url and bearer auth
- fixing splunk alert payload example path
- add return for HandleUpdate dryrun
- adds flag to disable LDAP lookups
=> adds flag to disable LDAP lookups

pkg/listeners/listeners.go, pkg/splunk/alert.go, pkg/splunk/result.go
This fixes a bug in which the alert name was the only thing entered in to the Jira issue body text.
This also fixes parsing of alert fields to properly grab the alert data from the formatted text fields.
REF: [OSD-21823](https://issues.redhat.com//browse/OSD-21823)
=> [OSD-21823] Properly parse alert details to Jira ticket body

pkg/splunk/alert_test.go, pkg/splunk/splunk_test.go
This adjusts the tests for Splunk alerts and alert retrieval to match
the new fields in the parsing functions.
Fixes OSD-21842
=>  [OSD-21842] Adjust tests to match new reasons, summary fields

deploy/compliance-audit-router-staging.yml
The env[].valueFrom.secretKeyRef format requires the secretKeyRef to be a dict with name and key. Previous versions only provided a string variable.  This PR fixes the format of the secretKeyRefs in the deployment, and adds variable parameters for them.
=> Fix secretKeyRef

deploy/compliance-audit-router.yml
Route creation should be handled in the app-interface namespace file,
rather than the deploy template.
=> Remove route from deploy template

build/Dockerfile
Update the Go version in CAR's Dockerfile `BUILDER_IMAGE` to go 1.21, to match the
go.mod version.
=> Bump Dockerfile Go version to 1.21

deploy/compliance-audit-router.yml
fixes the following error when applying the resources:
```
Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field DeploymentSpec.spec.replicas of type int32
```
=> fix replicas

deploy/compliance-audit-router.yml
Remove restartPolicy from deployment because it is not supported by App-Interface on
non-init containers.
=> Remove restartPolicy from deployment

deploy/compliance-audit-router.yml
The .spec section of the service in the deploy template was indented too
far, causing a parse error in App-Interface.  This "outdents" it to the
proper level.
=> Fix service .spec indent

deploy/compliance-audit-router.yml
The apiVersion field for the service in the deployment template should
be `core/v1`, not `apps/v1`.
=> Fix api version for service in deployment template

deploy/compliance-audit-router.yml
Apparenlty `core/v1` is not required for describing a K8S service
apiVersion, and `v1` is correct.
=> Adjust service apiVersion to v1

deploy/compliance-audit-router.yml
Reverting the deployment template `LISTEN_PORT` variable back to an
integer rather than a string.
=> Change $LISTEN_PORT variable to an integer

deploy/compliance-audit-router.yml
Turns out the template requires int values to be quoted in both the
parameter and around the referenced variable in the template, but are
then re-parsed properly as int when the template is processed.
I belive this is finally being parsed correctly:
```
oc process --parameters -f deploy/compliance-audit-router.yml
NAME                     DESCRIPTION         GENERATOR           VALUE
IMAGE_REGISTRY                                                   quay.io
IMAGE_REPOSITORY                                                 app-sre
IMAGE_NAME                                                       compliance-audit-router
IMAGE_TAG                                                        latest
IMAGE_PULL_SECRET                                                quay.io
JIRA_SECRET_REF_KEY …
```
=> Add quotes for parameter variable

deploy/compliance-audit-router.yml
Removing the unused ROUTE_* parametes, as the route is managed entirely
with app-interface.
=> Remove unused parameters

deploy/compliance-audit-router.yml
The integers in the deploy template should be quoted to allow them to be
parsed properly by the template.
=> Quote ints in deploy template

Makefile
Removes the search for go files in the root of the repo by the `make
license` target, as none exist, and it throws an error otherwise.
=> Fix license Makefile target

cmd/main.go
Adds a comment to the metric registration to remind that the /metric
path is handled by the registration, and not the go-chi initialized
routes.
ie: /metrics will be initialized even though it isn't  one of the go-chi
listeners
=> Add a note about metric path registration

pkg/config/config.go
If `CAR_DRYRUN=true` is specified, allow the app to continue startup even if
the configuration is invalid, and continue running in dry-run mode for
troubleshooting.
If `CAR_DRYRUN=false` or somehow unset (it should default to `true`),
then an invalid config will continue to log and immediately exit.
=> Continue in dry-run mode even if config is invalid
