openshift/compliance-audit-router

- cmd/main.go
- pkg/listeners/listeners.go
Simplifies how we initialize routes and cleans up unnecessary structs/functions.
> Simplify route initialization

- pkg/splunk/alert.go
- pkg/splunk/result.go
- pkg/splunk/splunk.go
* adds a structured type for AlertDetails
* changes SearchResult to be unstructured
> Normalize alert details

- OWNERS
Update OWNERS to include Team Rocket and update Security
> Adds Team Rocket members; updates Team Security membership, in OWNERS file

- README.md
- cmd/main.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/jira/jira.go
* Adds validation functions for required configuration information
* Adds unit tests for validation functions
* Updates README.md to document configuration information
> [OSD-18342] validate config on startup

- Makefile
- build/Dockerfile
- project.mk
Updates the Dockerfile to boilerplate standards and added a few make variables
> Updates Dockerfile/make targets to boilerplate standards

- Dockerfile
- adding symlink to Dockerfile for pipeline integration
> symlink dockerfile

- Makefile
- cmd/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/helpers/helpers.go
- pkg/jira/jira.go
- pkg/ldap/ldap.go
- pkg/ldap/ldap_test.go
- pkg/listeners/listeners.go
- pkg/listeners/listeners_test.go
- pkg/metrics/metrics.go
- pkg/splunk/alert.go
- pkg/splunk/alert_test.go
- pkg/splunk/result.go
- pkg/splunk/result_test.go
- pkg/splunk/splunk.go
- pkg/splunk/splunk_test.go
- Properly parse alert details to Jira ticket body
- Adds Makefile helper for updating license info; updates license info
> license helper

- README.md
Per https://issues.redhat.com/browse/OSD-22359
> Minor change to trigger image build

- deploy/compliance-audit-router-staging.yml
Adds a service deployment template for staging, with service and route
> Add deploy template for staging

- deploy/compliance-audit-router-staging.yml
Adds parameters to template and returns image value to parameterized string.
> Add parameters to deployment template

- deploy/compliance-audit-router-staging.yml
Fix yaml typo for deployment name and labels
> Fix yaml typo for deployment name and labels 

- deploy/compliance-audit-router-staging.yml
Add parameters and values to deploy template
> Add parameters to deploy template

- OWNERS_ALIASES
Add new Rocket and Security team members
> Add team members

- deploy/compliance-audit-router-staging.yml
- **Convert int to str - apparently the listen port value cannot be a "number".**
- **Switching replicas value from int to str for tests**
> deploy template

- deploy/compliance-audit-router-staging.yml
- deploy/compliance-audit-router.yml
* Make deployment generic with regards to staging/production as both environments will use it.
* Add VERBOSE and DRYRUN env/params
> Make template generic (stg/prod); add VERBOSE & DRYRUN params

- deploy/compliance-audit-router.yml
Adds the imagePullSecret field to the deployment template podspec.
> Adds field for imagePullSecret

- deploy/compliance-audit-router.yml
LISTEN_PORT should be an integer, not a string.
> Change LISTEN_PORT from string to int

- OWNERS_ALIASES
> remove achvatal from OWNERS_ALIASES

- deploy/compliance-audit-router.yml
Adds liveness and readiness checks to the CAR containers; reorders the
yaml to match the various k8s specs.
> Adds live- and readiness checks; reorders yaml to match spec

- deploy/compliance-audit-router.yml
remove quotes from ints;add missing "name" key to imagePullSecret(s) 
> remove quotes from ints;add missing "name" key to imagePullSecret(s)

- pkg/config/config.go
Fix parsing nested configs; add more verbose logging
* Fixes an error causing nested config values to fail to be retrieved from env variables.
* Adds more verbose logging to show what is being parsed.
* Hides potentially sensitive info from log.
> Fix parsing nested configs; add more verbose logging

- deploy/compliance-audit-router.yml
Adds final parameters for CAR config: hosts, project key, etc.
Fixes a minor case typo in revisionHistoryLimit.
> Adds final parameters for CAR config

- pkg/config/config.go
Adds default config values for non-sensitive fields
> Add default config values for non-sensitive fields

- cmd/main.go
- pkg/config/config.go
- pkg/jira/jira.go
- pkg/ldap/ldap.go
- pkg/ldap/ldap_test.go
- pkg/listeners/listeners.go
- pkg/splunk/splunk.go
Improves logging and error messages
> Improve logging and error messages
